<%@ Page Title="" Language="C#" MasterPageFile="~/Global.Master" AutoEventWireup="true" CodeBehind="Student.aspx.cs" Inherits="Comp229_Assign03.Student" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

    
        <asp:Label ID="studentTitle" runat="server" Text="Student: "></asp:Label>
        <asp:GridView ID="GridView1"  runat="server"  AutoGenerateDeleteButton="True" OnRowDeleting="student_GridView_RowDeleting"  Onrowupdating="Student_GridView_RowUpdating" onrowupdated="Student_GridView_RowUpdated" onrowcancelingedit="StudentGridView_RowCancelingEdit"  onrowediting="StudentGridView_RowEditing"  AutoGenerateColumns="False" autogenerateeditbutton="True"  Height="179px" HorizontalAlign="Center" Width="781px" BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px" CellPadding="3" CellSpacing="2" >
            <Columns>
        
                <asp:BoundField DataField="StudentID" HeaderText="StudentID" InsertVisible="False" ReadOnly="True"  />
                <asp:BoundField DataField="LastName" HeaderText="LastName" />
                <asp:BoundField DataField="FirstMidName" HeaderText="FirstMidName" />
                <asp:BoundField DataField="CourseID" HeaderText="Course ID" ReadOnly="True" />
                <asp:BoundField DataField="Title" HeaderText="Course Name" ReadOnly="True"/>
                <asp:BoundField DataField="Credits" HeaderText="Credit" ReadOnly="True"/>
                     
            </Columns>
            <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
            <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
            <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
            <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
            <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#FFF1D4" />
            <SortedAscendingHeaderStyle BackColor="#B95C30" />
            <SortedDescendingCellStyle BackColor="#F1E5CE" />
            <SortedDescendingHeaderStyle BackColor="#93451F" />
        </asp:GridView>
   

</asp:Content>
